# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSPayApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSPayApp
  pod 'BraintreeDropIn'

  target 'iOSPayAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSPayAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
